### ISSUE TITLE
vue logo is not displayed

### ISSUE THREAD

**Issue by rastislavsvoboda** [joeldenning/vite-single-spa-example#6] opened 2021-09-02 15:05 UTC
hallo

when running vite-single-spa-example in vite-signle-spa-root-config locally
nor in single spa playground
vue logo (image) is not displayed, just alt text

log in console:
single-spa-playground.org/:34 GET https://www.googletagmanager.com/gtag/js?id=UA-139580978-1 net::ERR_BLOCKED_BY_CLIENT

is this something wrong on my side?

**Comment by internettrans** [comment] 2021-09-20 03:28
Duplicate of https://github.com/joeldenning/vite-single-spa-example/issues/4. This is tracked in https://github.com/vitejs/vite/issues/3107

**Closed as completed by internettrans** 2021-09-20 03:28 UTC
